# Generated by Django 5.1.4 on 2025-03-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_recipe_shoppinglist_user_usermenu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
