# Generated by Django 5.1.7 on 2025-03-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userprofile_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
